<a href="https://colab.research.google.com/github/JoaoHHoffmann/analise-funcionarios/blob/main/anailseFuncionarios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Analisando o dataset employees.csv

In [45]:
import pandas as pd
df = pd.read_csv('/content/employees.csv')
df.head()

,ID,Nome,Idade,Cargo,Salário,Data_Admissão,Departamento
0,1,Ana Silva,34,Analista de Dados,7500,2018-03-15,TI
1,2,Carlos Lima,29,Cientista de Dados,10500,2020-07-10,TI
2,3,Beatriz Souza,41,Gerente de Projetos,15000,2015-11-25,Gestão
3,4,João Mendes,38,Desenvolvedor,8200,2017-09-08,TI
4,5,Fernanda Rocha,26,UX Designer,6700,2021-05-14,Design

## Selecionando apenas os funcionarios que trabalham com TI.

In [7]:
dep_ti = df[df['Departamento'] == 'TI']
dep_ti

,ID,Nome,Idade,Cargo,Salário,Data_Admissão,Departamento
0,1,Ana Silva,34,Analista de Dados,7500,2018-03-15,TI
1,2,Carlos Lima,29,Cientista de Dados,10500,2020-07-10,TI
3,4,João Mendes,38,Desenvolvedor,8200,2017-09-08,TI
5,6,Marcos Andrade,32,Engenheiro de Software,11500,2019-02-21,TI
6,7,Luciana Alves,30,DBA,9800,2022-06-30,TI
10,11,Vanessa Martins,45,Arquiteto de Software,14500,2014-08-15,TI
11,12,Thiago Ribeiro,31,Desenvolvedor,8600,2019-10-23,TI
13,14,Fernando Duarte,39,Analista de Sistemas,9100,2016-07-18,TI
15,16,Eduardo Gomes,35,Desenvolvedor Front-End,10200,2018-09-17,TI
16,17,Carolina Ribeiro,33,Desenvolvedor Back-End,10700,2019-12-05,TI

## Encontrando a média salarial dos funcionarios

In [12]:
media_salario = df['Salário'].mean()
print(f'A media salarial dessa empresa é de {media_salario:.2f}')

A media salarial dessa empresa é de 11540.00

## Filtrando os funcionarios que foram admitidos apos 2019

In [24]:
df['Data_Admissão'] = pd.to_datetime(df['Data_Admissão'])
admitidos_apos_2019 = df[df['Data_Admissão'].dt.year > 2019]
admitidos_apos_2019

,ID,Nome,Idade,Cargo,Salário,Data_Admissão,Departamento
1,2,Carlos Lima,29,Cientista de Dados,10500,2020-07-10,TI
4,5,Fernanda Rocha,26,UX Designer,6700,2021-05-14,Design
6,7,Luciana Alves,30,DBA,9800,2022-06-30,TI
14,15,Juliana Rocha,28,Analista de UX,7500,2020-03-22,Design

## Criando nova coluna que representa o tempo que o funcionario esta na empresa em anos

In [27]:
df['Tempo_Empresa'] = (pd.Timestamp.now() - pd.to_datetime(df['Data_Admissão'])).dt.days // 365
df

,ID,Nome,Idade,Cargo,Salário,Data_Admissão,Departamento,Tempo_Empresa
0,1,Ana Silva,34,Analista de Dados,7500,2018-03-15,TI,7
1,2,Carlos Lima,29,Cientista de Dados,10500,2020-07-10,TI,4
2,3,Beatriz Souza,41,Gerente de Projetos,15000,2015-11-25,Gestão,9
3,4,João Mendes,38,Desenvolvedor,8200,2017-09-08,TI,7
4,5,Fernanda Rocha,26,UX Designer,6700,2021-05-14,Design,3
5,6,Marcos Andrade,32,Engenheiro de Software,11500,2019-02-21,TI,6
6,7,Luciana Alves,30,DBA,9800,2022-06-30,TI,2
7,8,Ricardo Pinto,40,Analista de Segurança,8700,2016-04-10,Segurança,8
8,9,Gabriela Costa,27,Analista de BI,9200,2018-12-12,BI,6
9,10,Paulo Oliveira,36,Scrum Master,10800,2017-11-05,Gestão,7
10,11,Vanessa Martins,45,Arquiteto de Software,14500,2014-08-15,TI,10
11,12,Thiago Ribeiro,31,Desenvolvedor,8600,2019-10-23,TI,5
12,13,Patrícia Nunes,29,Gerente de TI,15800,2013-06-30,Gestão,11
13,14,Fernando Duarte,39,Analista de Sistemas,9100,2016-07-18,TI,8
14,15,Juliana Rocha,28,Analista de UX,7500,2020-03-22,Design,5
15,16,Eduardo Gomes,35,Desenvolvedor Front-End,10200,2018-09-17,TI,6
16,17,Carolina Ribeiro,33,Desenvolvedor Back-End,10700,2019-12-05,TI,5
17,18,Rodrigo Alves,37,Gerente de Infra,16500,2015-05-20,Infra,9
18,19,Mônica Cardoso,42,Diretor de TI,18000,2012-03-10,Gestão,13
19,20,Gustavo Lopes,50,CTO,22000,2010-01-05,Gestão,15

## Filtrando o funcionario mais velho e o mais novo

In [28]:
mais_velho = df[df['Tempo_Empresa'] == df['Tempo_Empresa'].max()]
mais_novo = df[df['Tempo_Empresa'] == df['Tempo_Empresa'].min()]
print('Funcionario mais velho: ')
display(mais_velho)
print('Funcionario mais novo: ')
display(mais_novo)

Funcionario mais velho:

,ID,Nome,Idade,Cargo,Salário,Data_Admissão,Departamento,Tempo_Empresa
19,20,Gustavo Lopes,50,CTO,22000,2010-01-05,Gestão,15

Funcionario mais novo:

,ID,Nome,Idade,Cargo,Salário,Data_Admissão,Departamento,Tempo_Empresa
6,7,Luciana Alves,30,DBA,9800,2022-06-30,TI,2

## Filtrando o cargo com o maior salario medio

In [41]:
cargo_maior_salario = df.groupby('Cargo')['Salário'].mean().idxmax()
maior_salario_medio = df.groupby('Cargo')['Salário'].mean().max()
print(f'O cargo com o maior salario medio é: {cargo_maior_salario}, com o valor de {maior_salario_medio:.2f}')

O cargo com o maior salario medio é: CTO, com o valor de 22000.00

## Agrupando os funcionarios por departamento e encontrando a media salarial de cada um dos departamentos

In [42]:
salario_medio = df.groupby('Departamento')['Salário'].mean()
display(salario_medio)

Departamento
BI            9200.0
Design        7100.0
Gestão       16320.0
Infra        16500.0
Segurança     8700.0
TI           10060.0
Name: Salário, dtype: float64

## Ordenando os funcionarios pelo tempo de empresa em ordem decrescente

In [44]:
tempo_empresa = df.sort_values(by='Tempo_Empresa', ascending=False)
display(tempo_empresa)

,ID,Nome,Idade,Cargo,Salário,Data_Admissão,Departamento,Tempo_Empresa
19,20,Gustavo Lopes,50,CTO,22000,2010-01-05,Gestão,15
18,19,Mônica Cardoso,42,Diretor de TI,18000,2012-03-10,Gestão,13
12,13,Patrícia Nunes,29,Gerente de TI,15800,2013-06-30,Gestão,11
10,11,Vanessa Martins,45,Arquiteto de Software,14500,2014-08-15,TI,10
17,18,Rodrigo Alves,37,Gerente de Infra,16500,2015-05-20,Infra,9
2,3,Beatriz Souza,41,Gerente de Projetos,15000,2015-11-25,Gestão,9
13,14,Fernando Duarte,39,Analista de Sistemas,9100,2016-07-18,TI,8
7,8,Ricardo Pinto,40,Analista de Segurança,8700,2016-04-10,Segurança,8
0,1,Ana Silva,34,Analista de Dados,7500,2018-03-15,TI,7
3,4,João Mendes,38,Desenvolvedor,8200,2017-09-08,TI,7
9,10,Paulo Oliveira,36,Scrum Master,10800,2017-11-05,Gestão,7
5,6,Marcos Andrade,32,Engenheiro de Software,11500,2019-02-21,TI,6
8,9,Gabriela Costa,27,Analista de BI,9200,2018-12-12,BI,6
15,16,Eduardo Gomes,35,Desenvolvedor Front-End,10200,2018-09-17,TI,6
14,15,Juliana Rocha,28,Analista de UX,7500,2020-03-22,Design,5
11,12,Thiago Ribeiro,31,Desenvolvedor,8600,2019-10-23,TI,5
16,17,Carolina Ribeiro,33,Desenvolvedor Back-End,10700,2019-12-05,TI,5
1,2,Carlos Lima,29,Cientista de Dados,10500,2020-07-10,TI,4
4,5,Fernanda Rocha,26,UX Designer,6700,2021-05-14,Design,3
6,7,Luciana Alves,30,DBA,9800,2022-06-30,TI,2